version: '3.9'
services:
  db: 
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    volumes:
      - ./data/pg/data:/var/lib/postgressql/data
      - ./data/pg/config:/etc/postgressql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

  backend:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - backend/.env
    depends_on:
      db:
        condition: service_healthy