version: '3.9'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/pg/data:/var/lib/postgressql/data
      - ./data/pg/config:/etc/postgressql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  #только сбилдит
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./static:/app/dist
  proxy:
    image: nginx:latest
    container_name: spo-proxy
    env_file:
      - .env
    volumes:
      - ~/static:/var/www/static
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./nginx/run_nginx.sh:/src/run_nginx.sh
    command: ./src/run_nginx.sh
    networks:
      - nginx-network
      - default
networks:
  nginx-network:
    external: true